### ISSUE TITLE
no podspec for macos

### ISSUE THREAD

**Issue by MichalNemec** [zezo357/flutter_meedu_videoplayer#40] opened 2023-03-31 14:20 UTC
when running pod install i get
```
[!] No podspec found for `flutter_meedu_videoplayer` in `Flutter/ephemeral/.symlinks/plugins/flutter_meedu_videoplayer/macos`
```

seems like gitignore settings issue from the plugin side?

**Comment by zezo357** [comment] 2023-03-31 14:23
> when running pod install i get
> 
> ```
> [!] No podspec found for `flutter_meedu_videoplayer` in `Flutter/ephemeral/.symlinks/plugins/flutter_meedu_videoplayer/macos`
> ```
> 
> seems like gitignore settings issue from the plugin side?

working on a fix, sorry for that

duplicate of https://github.com/zezo357/flutter_meedu_videoplayer/issues/38

**Closed by zezo357** 2023-03-31 14:23 UTC
