### ISSUE TITLE
Unable to launch app with Flutter 3.13

### ISSUE THREAD

**Issue by Mario359** [zezo357/flutter_meedu_videoplayer#162] opened 2023-08-17 12:58 UTC
Hello, today I have updated my project to Flutter 3.13.0 from Flutter 3.10.6 and Meedu videoplayer seems to not work properly with this version of Flutter.

I have created a new project with this package only and it still stop on launch

Error:
`Error connecting to the service protocol: failed to connect to http://127.0.0.1:60201/EyVDbLu8yCU=/`
Full error:
```
[  +70 ms] Connecting to service protocol: http://127.0.0.1:60658/-IKGTKRilio=/
[  +33 ms] Fail to connect to service protocol: http://127.0.0.1:60658/-IKGTKRilio=/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60658/-IKGTKRilio=/ws
[   +3 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:60658/-IKGTKRilio=/
[  +16 ms] "flutter run" took 62 028ms.
[   +7 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +113 ms] ensureAnalyticsSent: 96ms
[   +1 ms] Running 1 shutdown hook
[  +13 ms] Shutdown hooks complete
[   +1 ms] exiting with code 2
```
On Windows:
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/20285750/55b00eb6-5278-437a-a548-d1eab1f305a3)
This error is showing on Android and Windows, it seems that the app is installed but cannot start and abort connection

It works fine on Web, MacOS and iOS

**Comment by Mario359** [comment] 2023-08-17 13:38
I haven't implemented media_kit on my projects, I added the video_player package

**Comment by zezo357** [comment] 2023-08-17 13:41
Media_kit by default is used in windows so that explains windows, but this doesn't explain android


So it may be something else, when I test I will let you know, sadly I can't do that now

**Comment by annd22** [comment] 2023-08-17 17:46
confirm this happen on windows 11 (normal on windows 10), from 3.10.6.
if I remove the meedu lib, everythings is ok.

**Comment by zezo357** [comment] 2023-08-17 19:15
@annd22 I have windows 10, can you try media_kit and let me know if it does crash there or not?

Like the main example they have,

Also

does flutter upgrade help?

**Comment by annd22** [comment] 2023-08-18 02:28
> @annd22 I have windows 10, can you try media_kit and let me know if it does crash there or not?
> 
> Like the main example they have,
> 
> Also
> 
> does flutter upgrade help?

- did you mean that remove flutter_meedu_videoplayer and import media_kit only?

**Comment by zezo357** [comment] 2023-08-18 07:27
> > @annd22 I have windows 10, can you try media_kit and let me know if it does crash there or not?
> > 
> > Like the main example they have,
> > 
> > Also
> > 
> > does flutter upgrade help?
> 
> - did you mean that remove flutter_meedu_videoplayer and import media_kit only?
> 

Replace with flutter_meedu_media_kit and just comment what doesn't exist 

Wait a moment it happens on windows on launch right? Without opening any players??? If that's the case can you comment initmeedu? Maybe window manger is the one causing the crash

**Comment by bryanjorgeflores** [comment] 2023-08-18 13:42
I have the same problem, deleting the package allows me to debug

> Hello, today I have updated my project to Flutter 3.13.0 from Flutter 3.10.6 and Meedu videoplayer seems to not work properly with this version of Flutter.
> 
> I have created a new project with this package only and it still stop on launch
> 
> Error: `Error connecting to the service protocol: failed to connect to http://127.0.0.1:60201/EyVDbLu8yCU=/` Full error:
> 
> ```
> [  +70 ms] Connecting to service protocol: http://127.0.0.1:60658/-IKGTKRilio=/
> [  +33 ms] Fail to connect to service protocol: http://127.0.0.1:60658/-IKGTKRilio=/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60658/-IKGTKRilio=/ws
> [   +3 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:60658/-IKGTKRilio=/
> [  +16 ms] "flutter run" took 62 028ms.
> [   +7 ms]
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
>            <asynchronous suspension>
>            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
>            <asynchronous suspension>
>            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
>            <asynchronous suspension>
>            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
>            <asynchronous suspension>
>            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
>            <asynchronous suspension>
>            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
>            <asynchronous suspension>
>            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #10     main (package:flutter_tools/executable.dart:90:3)
>            <asynchronous suspension>
> 
> 
> [ +113 ms] ensureAnalyticsSent: 96ms
> [   +1 ms] Running 1 shutdown hook
> [  +13 ms] Shutdown hooks complete
> [   +1 ms] exiting with code 2
> ```
> 
> On Windows: ![image](https://user-images.githubusercontent.com/20285750/261314955-55b00eb6-5278-437a-a548-d1eab1f305a3.png) This error is showing on Android and Windows, it seems that the app is installed but cannot start and abort connection
> 
> It works fine on Web, MacOS and iOS

**Comment by annd22** [comment] 2023-08-18 15:08
> 
I tried:
- replace with `flutter_meedu_media_kit` is basiclly remove all `flutter_meedu_videoplayer` -> build normally
- just comment the `MediaKit.ensureInitialized();` -> still get the error

**Comment by zezo357** [comment] 2023-08-18 15:13
Can I ask you to try media_kit example on their repo? I am trying to pinpoint the crash cause 

Window_manager or media_kit

If you can try both packages examples that will help greatly since one will crash,

Since I couldnt replicate it 😢


Also I am planning to update the package to the latest version of media_kit tonight, hopefully that fixes it.

**Comment by annd22** [comment] 2023-08-18 15:34
I tried on windows 11, flutter 3.10.6 (on windows 10 still works normally):
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/83078116/c632cf3c-cefe-4162-8d08-1121a2f45fa4)
- remove `flutter_meedu_video_player` : build debug success ✅
- remove `flutter_meedu_video_player` and replace with `flutter_meedu_media_kit` 4.2.24+1:  build debug failed ❌
- only remove meedu init function `MediaKit.ensureInitialized();` and `initVideoPlayerMediaKitIfNeeded();`: build debug failed ❌
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/83078116/8ed264df-5d19-4051-97ac-1e3980107b50)

> > > @annd22 I have windows 10, can you try media_kit and let me know if it does crash there or not?
> > > Like the main example they have,
> > > Also
> > > does flutter upgrade help?
> > 
> > 
> > 
> > * did you mean that remove flutter_meedu_videoplayer and import media_kit only?
> 
> Replace with flutter_meedu_media_kit and just comment what doesn't exist
> 
> Wait a moment it happens on windows on launch right? Without opening any players??? If that's the case can you comment initmeedu? Maybe window manger is the one causing the crash

**Comment by zezo357** [comment] 2023-08-18 15:39
> I tried on windows 11, flutter 3.10.6 (on windows 10 still works normally):
> ![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/83078116/c632cf3c-cefe-4162-8d08-1121a2f45fa4)
> - remove `flutter_meedu_video_player` : build debug success ✅
> - remove `flutter_meedu_video_player` and replace with `flutter_meedu_media_kit` 4.2.24+1:  build debug failed ❌
> - only remove meedu init function `MediaKit.ensureInitialized();` and `initVideoPlayerMediaKitIfNeeded();`: build debug failed ❌
> ![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/83078116/8ed264df-5d19-4051-97ac-1e3980107b50)
> 
> > > > @annd22 I have windows 10, can you try media_kit and let me know if it does crash there or not?
> > > > Like the main example they have,
> > > > Also
> > > > does flutter upgrade help?
> > > 
> > > 
> > > 
> > > * did you mean that remove flutter_meedu_videoplayer and import media_kit only?
> > 
> > Replace with flutter_meedu_media_kit and just comment what doesn't exist
> > 
> > Wait a moment it happens on windows on launch right? Without opening any players??? If that's the case can you comment initmeedu? Maybe window manger is the one causing the crash
> 
> 

Right now I don't know the problem, can you please both window_manager and media_kit packages examples?

**Comment by annd22** [comment] 2023-08-18 15:46
I think its the media_kit.
My project contains `window_manager` as well, and you can see the 2 cases above:
```
remove flutter_meedu_video_player : build debug success ✅
remove flutter_meedu_video_player and replace with flutter_meedu_media_kit 4.2.24+1: build debug failed ❌
```
So we can have the conclusion is adding `flutter_meedu_media_kit` to a project - which contains `window_manager` before (and build normally) -> bug

**Comment by zezo357** [comment] 2023-08-18 16:24
> I think its the media_kit.
> My project contains `window_manager` as well, and you can see the 2 cases above:
> ```
> remove flutter_meedu_video_player : build debug success ✅
> remove flutter_meedu_video_player and replace with flutter_meedu_media_kit 4.2.24+1: build debug failed ❌
> ```
> So we can have the conclusion is adding `flutter_meedu_media_kit` to a project - which contains `window_manager` before (and build normally) -> bug 

Let me release the one with the latest version of media_kit and see if that helps

**Comment by AnonymHK** [comment] 2023-08-18 23:05
I also encountered the same problem, and after updating Flutter to 3.13, I also encountered the problem!

Error connecting to the service protocol: failed to connect to http://127.0.0.1:57693/cYuSJUuWHkc=/ 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [版本 10.0.19044.1889], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.5)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.70.0)
[√] Connected device (4 available)
[√] Network resources

 I tried to rollback the Flutter version and cleared the cache, but the problem persists! I created an example using the new version of Flutter and it works properly! Flutter_ Meedu_ Videoplayer_ Error running example:

√ Build build app outputs floppy apk app debug.apk

Installing build app outputs lutter apk app debug.apk

Error connecting to the service protocol: failed to connect to http://127.0.0.1:57693/cYuSJUuWHkc=/

My other Flutter projects are working properly!

**Comment by AnonymHK** [comment] 2023-08-18 23:07
After running, the app will appear blank and exit!

**Comment by zezo357** [comment] 2023-08-19 03:04
can you guys try this and let me know if it fixed it for you

for media_kit_libs_android_video put it only if you enabled media_kit for android 

also do a `flutter upgrade` before launching to get latest video_player_media_kit lib

dependency_overrides:
    media_kit: 1.1.2+1                              # Primary package.
  
    media_kit_video: 1.1.2                        # For video rendering.
        
    media_kit_libs_android_video: 1.3.0           # Android package for video native libraries.

**Comment by AnonymHK** [comment] 2023-08-19 12:34
> [在 media_kit media-kit/media-kit#378](https://github.com/media-kit/media-kit/issues/378)中提出了一个问题，希望他们能够更好地理解原因并找到更好的解决方案
> 
> 但是现在，你们可以尝试一下吗，让我知道它是否为您解决了这个问题
> 
> 对于 media_kit_libs_android_video 仅当您为 android 启用了 media_kit 时才放置它
> 
> 在启动之前还要执行一次`flutter upgrade`以获取最新的 video_player_media_kit lib
> 
> ```
> dependency_overrides:
>     media_kit: 1.1.2+1                              # Primary package.
>   
>     media_kit_video: 1.1.2                        # For video rendering.
>         
>     media_kit_libs_android_video: 1.3.0           # Android package for video native libraries.
> ```

This solution has solved my problem! Examples are running normally now!

**Comment by AnonymHK** [comment] 2023-08-19 13:01
By the way, consider upgrading the components under dependencies. Here is the latest stable version:

video_player_media_kit 0.0.24
volume_controller: ^2.0.7
screen_brightness: ^0.2.2
flutter_meedu: ^8.3.1
flutter_spinkit: ^5.2.0
shared_preferences: ^2.2.0
path_provider: ^2.1.0

**Comment by zezo357** [comment] 2023-08-19 13:12
The reason the overrides work is that on latest version of media_kit 

The find_packages module closes the app whenever it finds any package that uses media_kit in it's name which is not made by media_kit themselves, 


I think a better solution in their case is to just display a warning to developers instead of closing the app if the idea is to let people know it's not made by media_kit themselves. 


Let's see what they will say in the issue I opened (since I am just assuming that's what they want to do)

**Comment by bryanjorgeflores** [comment] 2023-08-19 13:26
Using the overrides fix the launch but now I get the next error:
<img width="1060" alt="image" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/43453756/c20643a7-af61-478b-91ac-1ae7181feedd">

**Comment by zezo357** [comment] 2023-08-19 13:40
> Using the overrides fix the launch but now I get the next error:
> <img width="1060" alt="image" src="https://github.com/zezo357/flutter_meedu_videoplayer/assets/43453756/c20643a7-af61-478b-91ac-1ae7181feedd">

Is that on Android? And you are using flutter_meedu_media_kit

Did you call mediakit ensure init? You can find it  
flutter_meedu_media_kit example

**Comment by bryanjorgeflores** [comment] 2023-08-19 13:46
> > Using the overrides fix the launch but now I get the next error:
> > <img alt="image" width="1060" src="https://user-images.githubusercontent.com/43453756/261800005-c20643a7-af61-478b-91ac-1ae7181feedd.png">
> 
> Is that on Android? And you are using flutter_meedu_media_kit
> 
> Did you call mediakit ensure init? You can find it flutter_meedu_media_kit example

Yeah I´m in android, I return to flutter_meedu_videoplayer cause i was trying the media_kit one. Now it's working fine, thank you!

**Comment by zezo357** [comment] 2023-08-19 14:09
I will update the package for now to use these versions to avoid the overrides, until media_kit resolves it.

**Comment by AnonymHK** [comment] 2023-08-19 14:15
> consider upgrading the components under dependencies. Here is the latest stable version:
> 
> video_player_media_kit 0.0.24 volume_controller: ^2.0.7 screen_brightness: ^0.2.2 flutter_meedu: ^8.3.1 flutter_spinkit: ^5.2.0 shared_preferences: ^2.2.0 path_provider: ^2.1.0

Consider upgrading the components under dependencies. Here is the latest stable version:

video_player_media_kit 0.0.24
volume_controller: ^2.0.7
screen_brightness: ^0.2.2
flutter_meedu: ^8.3.1
flutter_spinkit: ^5.2.0
shared_preferences: ^2.2.0
path_provider: ^2.1.0

**Comment by zezo357** [comment] 2023-08-19 14:21
> > consider upgrading the components under dependencies. Here is the latest stable version:
> > 
> > video_player_media_kit 0.0.24 volume_controller: ^2.0.7 screen_brightness: ^0.2.2 flutter_meedu: ^8.3.1 flutter_spinkit: ^5.2.0 shared_preferences: ^2.2.0 path_provider: ^2.1.0
> 
> Consider upgrading the components under dependencies. Here is the latest stable version:
> 
> video_player_media_kit 0.0.24
> volume_controller: ^2.0.7
> screen_brightness: ^0.2.2
> flutter_meedu: ^8.3.1
> flutter_spinkit: ^5.2.0
> shared_preferences: ^2.2.0
> path_provider: ^2.1.0

If it's not a major release flutter upgrade will work for all people, 

I try to avoid using latest version unless it fixes a bug in this package since it may cause conflicts with other people's packages.

**Comment by zezo357** [comment] 2023-08-19 15:03
i opened https://github.com/media-kit/media-kit/pull/382 hopefully they dont mind the change

**Comment by zezo357** [comment] 2023-08-19 15:11
also new release is live, check it (should not need a dependency_overrides)

also if you enabled media_kit for android use `media_kit_libs_android_video: 1.3.0`

**Comment by annd22** [comment] 2023-08-19 15:22
updated to `flutter_meedu_videoplayer: ^4.2.25` but still get the error on windows 11, flutter 3.10.6

**Comment by AnonymHK** [comment] 2023-08-19 15:25
flutter upgrade
flutter clean

**Comment by annd22** [comment] 2023-08-19 15:46
I tried, now flutter is 3.13, and still get error

> > updated to `flutter_meedu_videoplayer: ^4.2.25` but still get the error on windows 11, flutter 3.10.6
> 
> flutter upgrade flutter clean

**Comment by zezo357** [comment] 2023-08-19 16:06
> I tried, now flutter is 3.13, and still get error
> 
> > > updated to `flutter_meedu_videoplayer: ^4.2.25` but still get the error on windows 11, flutter 3.10.6
> > 
> > flutter upgrade flutter clean
> 
> 

On Android or windows? And does the overide work or not?

**Comment by annd22** [comment] 2023-08-19 16:22
on windows 11, I tried with and without dependency_overrides, and both not working
![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/83078116/fc4389b3-e2d1-4c2d-9da9-303b7ba4e4ca)

**Comment by zezo357** [comment] 2023-08-19 16:29
> on windows 11, I tried with and without dependency_overrides, and both not working
> ![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/83078116/fc4389b3-e2d1-4c2d-9da9-303b7ba4e4ca)
> 

Sadly I don't have a way to test windows 11 to figure out the cause of it 


Since it happens on both versions of flutter it may be safe to assume it's related to media_kit 


Can you try to override the media_kit windows video libs,
`media_kit_libs_windows_video: ^1.0.6`

**Comment by annd22** [comment] 2023-08-19 16:45
```
dependency_overrides:
  media_kit_libs_windows_video: 1.0.6   
```
this works, thank you 👍

**Comment by zezo357** [comment] 2023-08-19 16:54
> ```
> dependency_overrides:
>   media_kit_libs_windows_video: 1.0.6   
> ```
> this works, thank you 👍

Okay so as I thought the latest release of everything has the find packages module in which it crashes on launch

Hope they fix that with a warning instead of the exit

**Comment by zezo357** [comment] 2023-08-19 17:52
> ```
> dependency_overrides:
>   media_kit_libs_windows_video: 1.0.6   
> ```
> 
> this works, thank you 👍

published new release.

**Comment by zezo357** [comment] 2023-08-21 18:24
please check new release

**Comment by Mario359** [comment] 2023-08-22 17:28
I confirm it works on Windows 11 and Android, this issue can now be closed

**Closed** 2023-08-22 17:28 UTC
